using System;
using System.Collections.Generic;

namespace RentoomBookingWeb.Services.Localization
{
    // AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
    // Run route_generator.py to update this file based on .resx resources.
    public static class LocalizedRouteRegistry
    {
        public static readonly Dictionary<string, Dictionary<string, string>> PageSlugs = new()
        {
            ["Apartments"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["bs"] = "stanovi",
                ["cs"] = "byty",
                ["da"] = "lejligheder",
                ["de"] = "wohnungen",
                ["en"] = "apartments",
                ["en-us"] = "apartments",
                ["es"] = "apartamentos",
                ["et"] = "korterid",
                ["fi"] = "asunnot",
                ["fr"] = "appartements",
                ["ga"] = "arasain",
                ["hr"] = "stanovi",
                ["hu"] = "lakasok",
                ["is"] = "ibuir",
                ["it"] = "appartamenti",
                ["lt"] = "apartamentai",
                ["lv"] = "dzivokli",
                ["mt"] = "appartamenti",
                ["nl"] = "appartementen",
                ["no"] = "leiligheter",
                ["pl"] = "apartamenty",
                ["pl-pl"] = "apartamenty",
                ["pt"] = "apartamentos",
                ["ro"] = "apartamente",
                ["sk"] = "byty",
                ["sl"] = "stanovanja",
                ["sq"] = "apartamente",
                ["sr"] = "apartmani-novi-vino",
                ["sv"] = "lagenheter",
            },
            ["Contact"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["bs"] = "kontakt",
                ["cs"] = "kontakt",
                ["da"] = "kontakt",
                ["de"] = "kontakt",
                ["en"] = "contact",
                ["en-us"] = "contact",
                ["es"] = "contacto",
                ["et"] = "kontakt",
                ["fi"] = "yhteystiedot",
                ["fr"] = "contact",
                ["ga"] = "teagmhail",
                ["hr"] = "kontakt",
                ["hu"] = "kapcsolat",
                ["is"] = "samband",
                ["it"] = "contatto",
                ["lt"] = "kontaktai",
                ["lv"] = "kontakti",
                ["mt"] = "kuntatt",
                ["nl"] = "contact",
                ["no"] = "kontakt",
                ["pl"] = "kontakt",
                ["pl-pl"] = "kontakt",
                ["pt"] = "contato",
                ["ro"] = "contact",
                ["sk"] = "kontakt",
                ["sl"] = "stik",
                ["sq"] = "kontaktoni",
                ["sr"] = "napomena",
                ["sv"] = "kontakt",
            },
            ["Cooperation"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["bs"] = "saradnja",
                ["cs"] = "spoluprace",
                ["da"] = "samarbejde",
                ["de"] = "zusammenarbeit",
                ["en"] = "cooperation",
                ["en-us"] = "cooperation",
                ["es"] = "cooperacion",
                ["et"] = "koostoo",
                ["fi"] = "yhteistyo",
                ["fr"] = "cooperation",
                ["ga"] = "comhar",
                ["hr"] = "suradnja",
                ["hu"] = "egyuttmukodes",
                ["is"] = "samstarf",
                ["it"] = "cooperazione",
                ["lt"] = "bendradarbiavimas",
                ["lv"] = "sadarbiba",
                ["mt"] = "kooperazzjoni",
                ["nl"] = "samenwerking",
                ["no"] = "samarbeid",
                ["pl"] = "wspolpraca",
                ["pl-pl"] = "wspolpraca",
                ["pt"] = "cooperacao",
                ["ro"] = "cooperare",
                ["sk"] = "spolupraca",
                ["sl"] = "sodelovanje",
                ["sq"] = "bashkepunimi",
                ["sr"] = "saradnja",
                ["sv"] = "samarbete",
            },
            ["Statute"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["bs"] = "uslovi-i-odredbe",
                ["cs"] = "podminky",
                ["da"] = "vilkar-og-betingelser",
                ["de"] = "geschafts--und-kaufbedingungen",
                ["en"] = "regulations",
                ["en-us"] = "regulations",
                ["es"] = "terminos-y-condiciones",
                ["et"] = "tingimused-ja-tingimused",
                ["fi"] = "kayttoehdot",
                ["fr"] = "conditions-generales",
                ["ga"] = "tearmai-agus-coinniollacha",
                ["hr"] = "uvjeti-koristenja",
                ["hu"] = "feltetelek",
                ["is"] = "skilmalar-og-skilyri",
                ["it"] = "termini-e-condizioni",
                ["lt"] = "taisykles-ir-salygos",
                ["lv"] = "noteikumi-un-nosacijumi",
                ["mt"] = "termini-u-kundizzjonijiet",
                ["nl"] = "algemene-voorwaarden",
                ["no"] = "vilkar-og-betingelser",
                ["pl"] = "regulaminy",
                ["pl-pl"] = "regulaminy",
                ["pt"] = "termos-e-condicoes",
                ["ro"] = "termeni-si-conditii",
                ["sk"] = "obchodne-podmienky",
                ["sl"] = "pogoji-uporabe",
                ["sq"] = "termat-dhe-kushtet",
                ["sr"] = "uslovi-koriscenja",
                ["sv"] = "villkor-och-villkor",
            },
        };
    }
}
