// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentoomBooking.Api.LiveChat.Data;

#nullable disable

namespace RentoomBooking.Api.LiveChat.Migrations
{
    [DbContext(typeof(LiveChatDbContext))]
    [Migration("20260420040204_InitLiveChat")]
    partial class InitLiveChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentoomBooking.Api.LiveChat.Entities.LiveChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BitrixMessageId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("idx_livechat_messages_session_created_at");

                    b.ToTable("livechat_messages");
                });

            modelBuilder.Entity("RentoomBooking.Api.LiveChat.Entities.LiveChatSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BitrixChatId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_chat_id");

                    b.Property<string>("BitrixSessionId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("text")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .HasColumnType("text")
                        .HasColumnName("guest_name");

                    b.Property<string>("ReservationToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reservation_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ReservationToken", "Status")
                        .HasDatabaseName("idx_livechat_sessions_token_status");

                    b.ToTable("livechat_sessions");
                });

            modelBuilder.Entity("RentoomBooking.Api.LiveChat.Entities.LiveChatMessageEntity", b =>
                {
                    b.HasOne("RentoomBooking.Api.LiveChat.Entities.LiveChatSessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RentoomBooking.Api.LiveChat.Entities.LiveChatSessionEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
