// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentoomBooking.LiveChat.Data;

#nullable disable

namespace RentoomBooking.LiveChat.Migrations
{
    [DbContext(typeof(LiveChatDbContext))]
    [Migration("20260421001000_AddLiveChatCrmBinding")]
    partial class AddLiveChatCrmBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentoomBooking.LiveChat.Entities.BitrixLiveChatPortalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<string>("ApplicationToken")
                        .HasColumnType("text")
                        .HasColumnName("application_token");

                    b.Property<string>("ClientEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_endpoint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<long?>("EventHandlerId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_handler_id");

                    b.Property<string>("EventHandlerUrl")
                        .HasColumnType("text")
                        .HasColumnName("event_handler_url");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("ServerEndpoint")
                        .HasColumnType("text")
                        .HasColumnName("server_endpoint");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("idx_bitrix_livechat_portals_domain");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("idx_bitrix_livechat_portals_member_id");

                    b.ToTable("bitrix_livechat_portals");
                });

            modelBuilder.Entity("RentoomBooking.LiveChat.Entities.LiveChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BitrixMessageId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("OperatorAvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("operator_avatar_url");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text")
                        .HasColumnName("operator_name");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("idx_livechat_messages_session_created_at");

                    b.ToTable("livechat_messages");
                });

            modelBuilder.Entity("RentoomBooking.LiveChat.Entities.LiveChatSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BitrixChatId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_chat_id");

                    b.Property<DateTime?>("BitrixCrmBoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bitrix_crm_bound_at");

                    b.Property<int?>("BitrixCrmEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("bitrix_crm_entity_id");

                    b.Property<string>("BitrixCrmEntityType")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_crm_entity_type");

                    b.Property<string>("BitrixSessionId")
                        .HasColumnType("text")
                        .HasColumnName("bitrix_session_id");

                    b.Property<int?>("ClientBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("client_bitrix_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DealBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_bitrix_id");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("text")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .HasColumnType("text")
                        .HasColumnName("guest_name");

                    b.Property<int?>("IdoReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("ido_reservation_id");

                    b.Property<Guid?>("ReservationGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_guid");

                    b.Property<string>("ReservationToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reservation_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ReservationToken", "Status")
                        .HasDatabaseName("idx_livechat_sessions_token_status");

                    b.ToTable("livechat_sessions");
                });

            modelBuilder.Entity("RentoomBooking.LiveChat.Entities.LiveChatMessageEntity", b =>
                {
                    b.HasOne("RentoomBooking.LiveChat.Entities.LiveChatSessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RentoomBooking.LiveChat.Entities.LiveChatSessionEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
