//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBooking.StayWell.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBooking.StayWell.Resources.Pages.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AboutReservation {
            get {
                return ResourceManager.GetString("AboutReservation", resourceCulture);
            }
        }
        
        internal static string BookOnBtn {
            get {
                return ResourceManager.GetString("BookOnBtn", resourceCulture);
            }
        }
        
        internal static string BookOnDesc {
            get {
                return ResourceManager.GetString("BookOnDesc", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        internal static string CheckInNow {
            get {
                return ResourceManager.GetString("CheckInNow", resourceCulture);
            }
        }
        
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        internal static string ClubBenefits {
            get {
                return ResourceManager.GetString("ClubBenefits", resourceCulture);
            }
        }
        
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        internal static string Enhance {
            get {
                return ResourceManager.GetString("Enhance", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        internal static string InstructionsFooter {
            get {
                return ResourceManager.GetString("InstructionsFooter", resourceCulture);
            }
        }
        
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        internal static string ManageStay {
            get {
                return ResourceManager.GetString("ManageStay", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string MyVouchers {
            get {
                return ResourceManager.GetString("MyVouchers", resourceCulture);
            }
        }
        
        internal static string NoSuchPage {
            get {
                return ResourceManager.GetString("NoSuchPage", resourceCulture);
            }
        }
        
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        internal static string OpenApartment {
            get {
                return ResourceManager.GetString("OpenApartment", resourceCulture);
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string ReservationID {
            get {
                return ResourceManager.GetString("ReservationID", resourceCulture);
            }
        }
        
        internal static string ReservationCanceledTitle {
            get {
                return ResourceManager.GetString("ReservationCanceledTitle", resourceCulture);
            }
        }
        
        internal static string ReservationCanceledDesc {
            get {
                return ResourceManager.GetString("ReservationCanceledDesc", resourceCulture);
            }
        }
        
        internal static string ReservationExpiredTitle {
            get {
                return ResourceManager.GetString("ReservationExpiredTitle", resourceCulture);
            }
        }
        
        internal static string ReservationExpiredDesc {
            get {
                return ResourceManager.GetString("ReservationExpiredDesc", resourceCulture);
            }
        }
        
        internal static string AiChatTitle {
            get {
                return ResourceManager.GetString("AiChatTitle", resourceCulture);
            }
        }
        
        internal static string AiAssistant {
            get {
                return ResourceManager.GetString("AiAssistant", resourceCulture);
            }
        }
        
        internal static string ParkingFooter {
            get {
                return ResourceManager.GetString("ParkingFooter", resourceCulture);
            }
        }
        
        internal static string AboutReservationFooter {
            get {
                return ResourceManager.GetString("AboutReservationFooter", resourceCulture);
            }
        }
        
        internal static string LoyaltyFooter {
            get {
                return ResourceManager.GetString("LoyaltyFooter", resourceCulture);
            }
        }
        
        internal static string AddonsLabel {
            get {
                return ResourceManager.GetString("AddonsLabel", resourceCulture);
            }
        }
        
        internal static string CartButtonAlt {
            get {
                return ResourceManager.GetString("CartButtonAlt", resourceCulture);
            }
        }
        
        internal static string WifiFooter {
            get {
                return ResourceManager.GetString("WifiFooter", resourceCulture);
            }
        }
        
        internal static string TranslationDisclaimer {
            get {
                return ResourceManager.GetString("TranslationDisclaimer", resourceCulture);
            }
        }
    }
}
