//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutUs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.AboutUs", typeof(AboutUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        internal static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        internal static string ApartmentsManagement {
            get {
                return ResourceManager.GetString("ApartmentsManagement", resourceCulture);
            }
        }
        
        internal static string CompletedBookings {
            get {
                return ResourceManager.GetString("CompletedBookings", resourceCulture);
            }
        }
        
        internal static string QuestsServed {
            get {
                return ResourceManager.GetString("QuestsServed", resourceCulture);
            }
        }
        
        internal static string HistoryText1 {
            get {
                return ResourceManager.GetString("HistoryText1", resourceCulture);
            }
        }
        
        internal static string HistoryText2 {
            get {
                return ResourceManager.GetString("HistoryText2", resourceCulture);
            }
        }
        
        internal static string MissionText1 {
            get {
                return ResourceManager.GetString("MissionText1", resourceCulture);
            }
        }
        
        internal static string MissionText2 {
            get {
                return ResourceManager.GetString("MissionText2", resourceCulture);
            }
        }
        
        internal static string OurTeamText {
            get {
                return ResourceManager.GetString("OurTeamText", resourceCulture);
            }
        }
        
        internal static string TomaszText1 {
            get {
                return ResourceManager.GetString("TomaszText1", resourceCulture);
            }
        }
        
        internal static string KamilText {
            get {
                return ResourceManager.GetString("KamilText", resourceCulture);
            }
        }
        
        internal static string MartaText1 {
            get {
                return ResourceManager.GetString("MartaText1", resourceCulture);
            }
        }
        
        internal static string CallText {
            get {
                return ResourceManager.GetString("CallText", resourceCulture);
            }
        }
    }
}
