//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Apartments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apartments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentoomBookingWeb.Resources.Apartments", typeof(Apartments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Rentoom apartments. Comfort, great locations, and high standards for holidays and business stays..
        /// </summary>
        internal static string Apartments_SeoDescriptionDefault {
            get {
                return ResourceManager.GetString("Apartments_SeoDescriptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check available apartments for {0} - {1}. We found {2} offers tailored for you. Book securely online..
        /// </summary>
        internal static string Apartments_SeoDescriptionSearch {
            get {
                return ResourceManager.GetString("Apartments_SeoDescriptionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury apartments for rent - Rentoom.
        /// </summary>
        internal static string Apartments_SeoTitleDefault {
            get {
                return ResourceManager.GetString("Apartments_SeoTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apartments available for these dates - Rentoom.
        /// </summary>
        internal static string Apartments_SeoTitleNoOffers {
            get {
                return ResourceManager.GetString("Apartments_SeoTitleNoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results: {0} offers - Rentoom.
        /// </summary>
        internal static string Apartments_SeoTitleSearchWithOffers {
            get {
                return ResourceManager.GetString("Apartments_SeoTitleSearchWithOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ApartmentsNumber {
            get {
                return ResourceManager.GetString("ApartmentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ApartmentsText {
            get {
                return ResourceManager.GetString("ApartmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AvailableOffers {
            get {
                return ResourceManager.GetString("AvailableOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Balkon {
            get {
                return ResourceManager.GetString("Balkon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Centrum {
            get {
                return ResourceManager.GetString("Centrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dostęp_dla_wózków_inwalidzkich {
            get {
                return ResourceManager.GetString("Dostęp dla wózków inwalidzkich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Garaż {
            get {
                return ResourceManager.GetString("Garaż", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MandatoryOptions {
            get {
                return ResourceManager.GetString("MandatoryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment area.
        /// </summary>
        internal static string Map_AltArea {
            get {
                return ResourceManager.GetString("Map_AltArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bathrooms.
        /// </summary>
        internal static string Map_AltBathrooms {
            get {
                return ResourceManager.GetString("Map_AltBathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of beds.
        /// </summary>
        internal static string Map_AltBeds {
            get {
                return ResourceManager.GetString("Map_AltBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests.
        /// </summary>
        internal static string Map_AltGuests {
            get {
                return ResourceManager.GetString("Map_AltGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Map_ApartmentImageAlt {
            get {
                return ResourceManager.GetString("Map_ApartmentImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartments.
        /// </summary>
        internal static string Map_ClusterApartmentsPrefix {
            get {
                return ResourceManager.GetString("Map_ClusterApartmentsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no offers.
        /// </summary>
        internal static string Map_ClusterNoOffers {
            get {
                return ResourceManager.GetString("Map_ClusterNoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string Map_ClusterOffersPrefix {
            get {
                return ResourceManager.GetString("Map_ClusterOffersPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoOffersText1 {
            get {
                return ResourceManager.GetString("NoOffersText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoOfferText2 {
            get {
                return ResourceManager.GetString("NoOfferText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for stay.
        /// </summary>
        internal static string OfferPriceMapLabel {
            get {
                return ResourceManager.GetString("OfferPriceMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pralka {
            get {
                return ResourceManager.GetString("Pralka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelectedPackage {
            get {
                return ResourceManager.GetString("SelectedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Stare_Miasto {
            get {
                return ResourceManager.GetString("Stare Miasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuggestedDate {
            get {
                return ResourceManager.GetString("SuggestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuggestedDateFoundText {
            get {
                return ResourceManager.GetString("SuggestedDateFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuggestedDateLoading {
            get {
                return ResourceManager.GetString("SuggestedDateLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SuggestedDateNotFoundText {
            get {
                return ResourceManager.GetString("SuggestedDateNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WhereCheckIn {
            get {
                return ResourceManager.GetString("WhereCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Winda {
            get {
                return ResourceManager.GetString("Winda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Zwierzęta_dozwolone {
            get {
                return ResourceManager.GetString("Zwierzęta dozwolone", resourceCulture);
            }
        }
    }
}
