//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Apartment {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apartment() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Apartment", typeof(Apartment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApartmentName {
            get {
                return ResourceManager.GetString("ApartmentName", resourceCulture);
            }
        }
        
        internal static string SelectedDates {
            get {
                return ResourceManager.GetString("SelectedDates", resourceCulture);
            }
        }
        
        internal static string NoDatesSelected {
            get {
                return ResourceManager.GetString("NoDatesSelected", resourceCulture);
            }
        }
        
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        internal static string NoGuestsSelected {
            get {
                return ResourceManager.GetString("NoGuestsSelected", resourceCulture);
            }
        }
        
        internal static string NoOffersAvailable {
            get {
                return ResourceManager.GetString("NoOffersAvailable", resourceCulture);
            }
        }
        
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        internal static string AdditionalOptions {
            get {
                return ResourceManager.GetString("AdditionalOptions", resourceCulture);
            }
        }
        
        internal static string Opłata_serwisowa_139_x {
            get {
                return ResourceManager.GetString("Opłata serwisowa 139 x", resourceCulture);
            }
        }
        
        internal static string Zwierzę {
            get {
                return ResourceManager.GetString("Zwierzę", resourceCulture);
            }
        }
        
        internal static string Łóżeczko_dla_niemowlaka {
            get {
                return ResourceManager.GetString("Łóżeczko dla niemowlaka", resourceCulture);
            }
        }
        
        internal static string Łóżeczko_turystyczne {
            get {
                return ResourceManager.GetString("Łóżeczko turystyczne", resourceCulture);
            }
        }
        
        internal static string PÓŹNE_WYMELDOWANIE {
            get {
                return ResourceManager.GetString("PÓŹNE WYMELDOWANIE", resourceCulture);
            }
        }
        
        internal static string WCZESNE_ZAMELDOWANIE {
            get {
                return ResourceManager.GetString("WCZESNE ZAMELDOWANIE", resourceCulture);
            }
        }
        
        internal static string Kwiaty {
            get {
                return ResourceManager.GetString("Kwiaty", resourceCulture);
            }
        }
        
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        internal static string RefundableOffer {
            get {
                return ResourceManager.GetString("RefundableOffer", resourceCulture);
            }
        }
        
        internal static string Non_refundableOffer {
            get {
                return ResourceManager.GetString("Non-refundableOffer", resourceCulture);
            }
        }
        
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        internal static string SuggestedDate {
            get {
                return ResourceManager.GetString("SuggestedDate", resourceCulture);
            }
        }
        
        internal static string SuggestedDateLoading {
            get {
                return ResourceManager.GetString("SuggestedDateLoading", resourceCulture);
            }
        }
        
        internal static string NonRefundableText {
            get {
                return ResourceManager.GetString("NonRefundableText", resourceCulture);
            }
        }
        
        internal static string RefundableOfferText {
            get {
                return ResourceManager.GetString("RefundableOfferText", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string MandatoryOptions {
            get {
                return ResourceManager.GetString("MandatoryOptions", resourceCulture);
            }
        }
        
        internal static string ApartmentsMap {
            get {
                return ResourceManager.GetString("ApartmentsMap", resourceCulture);
            }
        }
        
        internal static string CleaningIncluded {
            get {
                return ResourceManager.GetString("CleaningIncluded", resourceCulture);
            }
        }
        
        internal static string SelectOffer {
            get {
                return ResourceManager.GetString("SelectOffer", resourceCulture);
            }
        }
        
        internal static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        internal static string ClickToCheckDetails {
            get {
                return ResourceManager.GetString("ClickToCheckDetails", resourceCulture);
            }
        }
        
        internal static string SelectDatesAndGuests {
            get {
                return ResourceManager.GetString("SelectDatesAndGuests", resourceCulture);
            }
        }
    }
}
