//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Apartments {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apartments() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Apartments", typeof(Apartments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApartmentsText {
            get {
                return ResourceManager.GetString("ApartmentsText", resourceCulture);
            }
        }
        
        internal static string ApartmentsNumber {
            get {
                return ResourceManager.GetString("ApartmentsNumber", resourceCulture);
            }
        }
        
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        internal static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string NoOffersText1 {
            get {
                return ResourceManager.GetString("NoOffersText1", resourceCulture);
            }
        }
        
        internal static string WhereCheckIn {
            get {
                return ResourceManager.GetString("WhereCheckIn", resourceCulture);
            }
        }
        
        internal static string SuggestedDate {
            get {
                return ResourceManager.GetString("SuggestedDate", resourceCulture);
            }
        }
        
        internal static string NoOfferText2 {
            get {
                return ResourceManager.GetString("NoOfferText2", resourceCulture);
            }
        }
        
        internal static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        internal static string Stare_Miasto {
            get {
                return ResourceManager.GetString("Stare Miasto", resourceCulture);
            }
        }
        
        internal static string Centrum {
            get {
                return ResourceManager.GetString("Centrum", resourceCulture);
            }
        }
        
        internal static string Garaż {
            get {
                return ResourceManager.GetString("Garaż", resourceCulture);
            }
        }
        
        internal static string Balkon {
            get {
                return ResourceManager.GetString("Balkon", resourceCulture);
            }
        }
        
        internal static string Zwierzęta_dozwolone {
            get {
                return ResourceManager.GetString("Zwierzęta dozwolone", resourceCulture);
            }
        }
        
        internal static string Winda {
            get {
                return ResourceManager.GetString("Winda", resourceCulture);
            }
        }
        
        internal static string Dostęp_dla_wózków_inwalidzkich {
            get {
                return ResourceManager.GetString("Dostęp dla wózków inwalidzkich", resourceCulture);
            }
        }
        
        internal static string Pralka {
            get {
                return ResourceManager.GetString("Pralka", resourceCulture);
            }
        }
        
        internal static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        internal static string AvailableOffers {
            get {
                return ResourceManager.GetString("AvailableOffers", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
    }
}
