//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cooperation {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cooperation() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Cooperation", typeof(Cooperation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CooperationText {
            get {
                return ResourceManager.GetString("CooperationText", resourceCulture);
            }
        }
        
        internal static string WhyUsText {
            get {
                return ResourceManager.GetString("WhyUsText", resourceCulture);
            }
        }
        
        internal static string ExperienceText1 {
            get {
                return ResourceManager.GetString("ExperienceText1", resourceCulture);
            }
        }
        
        internal static string ExperienceText2 {
            get {
                return ResourceManager.GetString("ExperienceText2", resourceCulture);
            }
        }
        
        internal static string Experience2Text {
            get {
                return ResourceManager.GetString("Experience2Text", resourceCulture);
            }
        }
        
        internal static string QualityText1 {
            get {
                return ResourceManager.GetString("QualityText1", resourceCulture);
            }
        }
        
        internal static string QualityText2 {
            get {
                return ResourceManager.GetString("QualityText2", resourceCulture);
            }
        }
        
        internal static string ProfessionalismText1 {
            get {
                return ResourceManager.GetString("ProfessionalismText1", resourceCulture);
            }
        }
        
        internal static string ProfessionalismText2 {
            get {
                return ResourceManager.GetString("ProfessionalismText2", resourceCulture);
            }
        }
        
        internal static string Professionalism2 {
            get {
                return ResourceManager.GetString("Professionalism2", resourceCulture);
            }
        }
        
        internal static string InnovationText1 {
            get {
                return ResourceManager.GetString("InnovationText1", resourceCulture);
            }
        }
        
        internal static string InnovationText2 {
            get {
                return ResourceManager.GetString("InnovationText2", resourceCulture);
            }
        }
        
        internal static string AdvantagesOfCooperation {
            get {
                return ResourceManager.GetString("AdvantagesOfCooperation", resourceCulture);
            }
        }
        
        internal static string Maintenance_freeInvestmentText1 {
            get {
                return ResourceManager.GetString("Maintenance-freeInvestmentText1", resourceCulture);
            }
        }
        
        internal static string Maintenance_freeInvestmentText2 {
            get {
                return ResourceManager.GetString("Maintenance-freeInvestmentText2", resourceCulture);
            }
        }
        
        internal static string IncomeOptimizationText1 {
            get {
                return ResourceManager.GetString("IncomeOptimizationText1", resourceCulture);
            }
        }
        
        internal static string IncomeOptimizationText2 {
            get {
                return ResourceManager.GetString("IncomeOptimizationText2", resourceCulture);
            }
        }
        
        internal static string ReadyToHelpText1 {
            get {
                return ResourceManager.GetString("ReadyToHelpText1", resourceCulture);
            }
        }
        
        internal static string ReadyToHelpText2 {
            get {
                return ResourceManager.GetString("ReadyToHelpText2", resourceCulture);
            }
        }
        
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        internal static string FillOutForm {
            get {
                return ResourceManager.GetString("FillOutForm", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string NumberOfApartments {
            get {
                return ResourceManager.GetString("NumberOfApartments", resourceCulture);
            }
        }
        
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string CooperationText1 {
            get {
                return ResourceManager.GetString("CooperationText1", resourceCulture);
            }
        }
    }
}
