//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Footer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Footer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentoomBookingWeb.Resources.Footer", typeof(Footer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutCity {
            get {
                return ResourceManager.GetString("AboutCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AllApartmentsText {
            get {
                return ResourceManager.GetString("AllApartmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CallUsText {
            get {
                return ResourceManager.GetString("CallUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string contactText {
            get {
                return ResourceManager.GetString("contactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DesignedText {
            get {
                return ResourceManager.GetString("DesignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentoom on Facebook.
        /// </summary>
        internal static string Footer_FacebookAriaLabel {
            get {
                return ResourceManager.GetString("Footer_FacebookAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Footer_FacebookIconAlt {
            get {
                return ResourceManager.GetString("Footer_FacebookIconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentoom on Instagram.
        /// </summary>
        internal static string Footer_InstagramAriaLabel {
            get {
                return ResourceManager.GetString("Footer_InstagramAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        internal static string Footer_InstagramIconAlt {
            get {
                return ResourceManager.GetString("Footer_InstagramIconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentoom - Apartments.
        /// </summary>
        internal static string Footer_LogoAlt {
            get {
                return ResourceManager.GetString("Footer_LogoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our partners.
        /// </summary>
        internal static string Footer_PartnersTitle {
            get {
                return ResourceManager.GetString("Footer_PartnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string footerText1 {
            get {
                return ResourceManager.GetString("footerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string LinksText {
            get {
                return ResourceManager.GetString("LinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Regulations1 {
            get {
                return ResourceManager.GetString("Regulations1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Regulations2 {
            get {
                return ResourceManager.GetString("Regulations2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegulationsLink {
            get {
                return ResourceManager.GetString("RegulationsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RegulationsText {
            get {
                return ResourceManager.GetString("RegulationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string SocialMediaLabel {
            get {
                return ResourceManager.GetString("SocialMediaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
    }
}
