//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Footer {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Footer() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Footer", typeof(Footer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string footerText1 {
            get {
                return ResourceManager.GetString("footerText1", resourceCulture);
            }
        }
        
        internal static string contactText {
            get {
                return ResourceManager.GetString("contactText", resourceCulture);
            }
        }
        
        internal static string CallUsText {
            get {
                return ResourceManager.GetString("CallUsText", resourceCulture);
            }
        }
        
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        internal static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
        
        internal static string RegulationsText {
            get {
                return ResourceManager.GetString("RegulationsText", resourceCulture);
            }
        }
        
        internal static string Regulations1 {
            get {
                return ResourceManager.GetString("Regulations1", resourceCulture);
            }
        }
        
        internal static string RegulationsLink {
            get {
                return ResourceManager.GetString("RegulationsLink", resourceCulture);
            }
        }
        
        internal static string Regulations2 {
            get {
                return ResourceManager.GetString("Regulations2", resourceCulture);
            }
        }
        
        internal static string AllApartmentsText {
            get {
                return ResourceManager.GetString("AllApartmentsText", resourceCulture);
            }
        }
        
        internal static string DesignedText {
            get {
                return ResourceManager.GetString("DesignedText", resourceCulture);
            }
        }
    }
}
