//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string title2 {
            get {
                return ResourceManager.GetString("title2", resourceCulture);
            }
        }
        
        internal static string title2subtitle {
            get {
                return ResourceManager.GetString("title2subtitle", resourceCulture);
            }
        }
        
        internal static string title3 {
            get {
                return ResourceManager.GetString("title3", resourceCulture);
            }
        }
        
        internal static string title3subtitle {
            get {
                return ResourceManager.GetString("title3subtitle", resourceCulture);
            }
        }
        
        internal static string text1title {
            get {
                return ResourceManager.GetString("text1title", resourceCulture);
            }
        }
        
        internal static string text1description {
            get {
                return ResourceManager.GetString("text1description", resourceCulture);
            }
        }
        
        internal static string clientsstat {
            get {
                return ResourceManager.GetString("clientsstat", resourceCulture);
            }
        }
        
        internal static string apartmentsstats {
            get {
                return ResourceManager.GetString("apartmentsstats", resourceCulture);
            }
        }
        
        internal static string locationsstats {
            get {
                return ResourceManager.GetString("locationsstats", resourceCulture);
            }
        }
        
        internal static string whyRentoom {
            get {
                return ResourceManager.GetString("whyRentoom", resourceCulture);
            }
        }
        
        internal static string whyRentoomTitle {
            get {
                return ResourceManager.GetString("whyRentoomTitle", resourceCulture);
            }
        }
        
        internal static string whyRentoomText1 {
            get {
                return ResourceManager.GetString("whyRentoomText1", resourceCulture);
            }
        }
        
        internal static string whyRentoomText2 {
            get {
                return ResourceManager.GetString("whyRentoomText2", resourceCulture);
            }
        }
        
        internal static string opinionText {
            get {
                return ResourceManager.GetString("opinionText", resourceCulture);
            }
        }
        
        internal static string formtext {
            get {
                return ResourceManager.GetString("formtext", resourceCulture);
            }
        }
        
        internal static string formContactText {
            get {
                return ResourceManager.GetString("formContactText", resourceCulture);
            }
        }
        
        internal static string formConfirm {
            get {
                return ResourceManager.GetString("formConfirm", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        internal static string text1title2 {
            get {
                return ResourceManager.GetString("text1title2", resourceCulture);
            }
        }
        
        internal static string text1description2 {
            get {
                return ResourceManager.GetString("text1description2", resourceCulture);
            }
        }
        
        internal static string whyRentoomSubtitle {
            get {
                return ResourceManager.GetString("whyRentoomSubtitle", resourceCulture);
            }
        }
    }
}
