//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Payment {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string IsInvoiceText {
            get {
                return ResourceManager.GetString("IsInvoiceText", resourceCulture);
            }
        }
        
        internal static string IsSaveInfoText {
            get {
                return ResourceManager.GetString("IsSaveInfoText", resourceCulture);
            }
        }
        
        internal static string ClickToDownloadInfo {
            get {
                return ResourceManager.GetString("ClickToDownloadInfo", resourceCulture);
            }
        }
        
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        internal static string ClientInfoButton {
            get {
                return ResourceManager.GetString("ClientInfoButton", resourceCulture);
            }
        }
        
        internal static string ClientInfoButtonLoading {
            get {
                return ResourceManager.GetString("ClientInfoButtonLoading", resourceCulture);
            }
        }
        
        internal static string ClientInfoTitle {
            get {
                return ResourceManager.GetString("ClientInfoTitle", resourceCulture);
            }
        }
        
        internal static string ClientInfoSubtitle {
            get {
                return ResourceManager.GetString("ClientInfoSubtitle", resourceCulture);
            }
        }
        
        internal static string YourStay {
            get {
                return ResourceManager.GetString("YourStay", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string SummaryText {
            get {
                return ResourceManager.GetString("SummaryText", resourceCulture);
            }
        }
        
        internal static string NightsText {
            get {
                return ResourceManager.GetString("NightsText", resourceCulture);
            }
        }
        
        internal static string SummaryLoadingText {
            get {
                return ResourceManager.GetString("SummaryLoadingText", resourceCulture);
            }
        }
        
        internal static string ReservationSummary {
            get {
                return ResourceManager.GetString("ReservationSummary", resourceCulture);
            }
        }
        
        internal static string SummaryDetailsText {
            get {
                return ResourceManager.GetString("SummaryDetailsText", resourceCulture);
            }
        }
        
        internal static string ReservationPaid {
            get {
                return ResourceManager.GetString("ReservationPaid", resourceCulture);
            }
        }
        
        internal static string ReservationPaidInfo {
            get {
                return ResourceManager.GetString("ReservationPaidInfo", resourceCulture);
            }
        }
        
        internal static string GoToStayWell {
            get {
                return ResourceManager.GetString("GoToStayWell", resourceCulture);
            }
        }
        
        internal static string ReservationPending {
            get {
                return ResourceManager.GetString("ReservationPending", resourceCulture);
            }
        }
        
        internal static string ReservationPendingInfo {
            get {
                return ResourceManager.GetString("ReservationPendingInfo", resourceCulture);
            }
        }
        
        internal static string ClickToPay {
            get {
                return ResourceManager.GetString("ClickToPay", resourceCulture);
            }
        }
        
        internal static string ReservationDanger {
            get {
                return ResourceManager.GetString("ReservationDanger", resourceCulture);
            }
        }
        
        internal static string ReservationDangerInfo {
            get {
                return ResourceManager.GetString("ReservationDangerInfo", resourceCulture);
            }
        }
        
        internal static string NameLastName {
            get {
                return ResourceManager.GetString("NameLastName", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        internal static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        internal static string ConfirmationNumber {
            get {
                return ResourceManager.GetString("ConfirmationNumber", resourceCulture);
            }
        }
        
        internal static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        internal static string PaymentSuccessfulText {
            get {
                return ResourceManager.GetString("PaymentSuccessfulText", resourceCulture);
            }
        }
        
        internal static string BackToSummary {
            get {
                return ResourceManager.GetString("BackToSummary", resourceCulture);
            }
        }
        
        internal static string ConfimationSendToMail {
            get {
                return ResourceManager.GetString("ConfimationSendToMail", resourceCulture);
            }
        }
        
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        internal static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        internal static string PaymentFailedText {
            get {
                return ResourceManager.GetString("PaymentFailedText", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string WaitingPayment {
            get {
                return ResourceManager.GetString("WaitingPayment", resourceCulture);
            }
        }
        
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        internal static string RedirectingToPayment {
            get {
                return ResourceManager.GetString("RedirectingToPayment", resourceCulture);
            }
        }
        
        internal static string RedirectToPaymentText {
            get {
                return ResourceManager.GetString("RedirectToPaymentText", resourceCulture);
            }
        }
        
        internal static string NotRefreshPage {
            get {
                return ResourceManager.GetString("NotRefreshPage", resourceCulture);
            }
        }
        
        internal static string CheckEmailText {
            get {
                return ResourceManager.GetString("CheckEmailText", resourceCulture);
            }
        }
        
        internal static string SendMailText {
            get {
                return ResourceManager.GetString("SendMailText", resourceCulture);
            }
        }
        
        internal static string ConfirmationWill {
            get {
                return ResourceManager.GetString("ConfirmationWill", resourceCulture);
            }
        }
        
        internal static string ConfirmationHasBeenSent {
            get {
                return ResourceManager.GetString("ConfirmationHasBeenSent", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string NoGusInfo {
            get {
                return ResourceManager.GetString("NoGusInfo", resourceCulture);
            }
        }
        
        internal static string GusError {
            get {
                return ResourceManager.GetString("GusError", resourceCulture);
            }
        }
        
        internal static string NoNipError {
            get {
                return ResourceManager.GetString("NoNipError", resourceCulture);
            }
        }
        
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string FillAllDataError {
            get {
                return ResourceManager.GetString("FillAllDataError", resourceCulture);
            }
        }
        
        internal static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
    }
}
