//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Apartments {
            get {
                return ResourceManager.GetString("Apartments", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string RentoomDesigner {
            get {
                return ResourceManager.GetString("RentoomDesigner", resourceCulture);
            }
        }
        
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        internal static string HomeHeroText {
            get {
                return ResourceManager.GetString("HomeHeroText", resourceCulture);
            }
        }
        
        internal static string NumberOfPeople {
            get {
                return ResourceManager.GetString("NumberOfPeople", resourceCulture);
            }
        }
        
        internal static string NumberOfRooms {
            get {
                return ResourceManager.GetString("NumberOfRooms", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string SelectNumberOfGuests {
            get {
                return ResourceManager.GetString("SelectNumberOfGuests", resourceCulture);
            }
        }
        
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        internal static string ChildrenUnder2 {
            get {
                return ResourceManager.GetString("ChildrenUnder2", resourceCulture);
            }
        }
        
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        internal static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        internal static string AdultSingle {
            get {
                return ResourceManager.GetString("AdultSingle", resourceCulture);
            }
        }
        
        internal static string AdultPlural {
            get {
                return ResourceManager.GetString("AdultPlural", resourceCulture);
            }
        }
        
        internal static string ChildSingle {
            get {
                return ResourceManager.GetString("ChildSingle", resourceCulture);
            }
        }
        
        internal static string ChildPlural {
            get {
                return ResourceManager.GetString("ChildPlural", resourceCulture);
            }
        }
        
        internal static string ClickToSelectDate {
            get {
                return ResourceManager.GetString("ClickToSelectDate", resourceCulture);
            }
        }
    }
}
