//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentoomBookingWeb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Upsell {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Upsell() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RentoomBookingWeb.Resources.Upsell", typeof(Upsell).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        internal static string ListSubtitle {
            get {
                return ResourceManager.GetString("ListSubtitle", resourceCulture);
            }
        }
        
        internal static string BadgeInfo {
            get {
                return ResourceManager.GetString("BadgeInfo", resourceCulture);
            }
        }
        
        internal static string Nights {
            get {
                return ResourceManager.GetString("Nights", resourceCulture);
            }
        }
        
        internal static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        internal static string TermsDescription {
            get {
                return ResourceManager.GetString("TermsDescription", resourceCulture);
            }
        }
    }
}
