// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentoomBooking.SharedClasses.Database;
using RentoomBooking.SharedClasses.Integrations.RentoomApp.Partners.Models;

#nullable disable

namespace RentoomBooking.SharedClasses.Migrations
{
    [DbContext(typeof(PostgresBookingDbContext))]
    [Migration("20260210180321_add_partner_service_snapshot_to_purchased_upsell_record")]
    partial class add_partner_service_snapshot_to_purchased_upsell_record
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerAgreedTerms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgreedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClientBitrixId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReservationGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("TermsSourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TermsSourceId");

                    b.ToTable("customer_agreed_terms");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerTermsAndConditionsSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("customer_terms_sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zgoda na przetwarzanie danych osobowych przez serwis Rentoom (Administratora danych) w celu realizacji usług",
                            IsRequired = true,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Regulamin główny serwisu i akceptacja IdoBooking",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zgoda na komunikację i przesyłanie ofert przez WhatsApp",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zgoda na przetwarzanie danych w systemie CRM Bitrix24",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zgoda marketingowa na przesyłanie ofert handlowych",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentAmenityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentAmenities");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentHashEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentHashes");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentInfos");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.DefinedAddonEntity", b =>
                {
                    b.Property<int>("IdoBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idobooking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdoBookingId"));

                    b.Property<string>("AddonDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("addon_definition");

                    b.Property<string>("AddonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addon_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<decimal>("PriceGross")
                        .HasColumnType("numeric")
                        .HasColumnName("price_gross");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric")
                        .HasColumnName("vat");

                    b.HasKey("IdoBookingId");

                    b.ToTable("defined_addons");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.RegistrationCardEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_mail");

                    b.Property<string>("GuestsData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("guests_data");

                    b.HasKey("ResToken");

                    b.ToTable("RegistrationCard");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.HasKey("ResToken");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationRecordEntity", b =>
                {
                    b.Property<Guid>("ReservationGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_guid");

                    b.Property<int?>("ClientBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("client_bitrix_id");

                    b.Property<string>("ConfirmationEmailBitrixId")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_email_bitrix_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DealBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_bitrix_id");

                    b.Property<int?>("IdoReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("ido_reservation_id");

                    b.Property<string>("IdoStatus")
                        .HasColumnType("text")
                        .HasColumnName("ido_status");

                    b.Property<Guid?>("PaymentSessionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_session_guid");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("ReservationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reservation_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ReservationGuid");

                    b.ToTable("reservation_records");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationTemplateEntity", b =>
                {
                    b.Property<string>("TemplateKey")
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TemplateKey");

                    b.ToTable("reservation_templates");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.SearchFiltersEntity", b =>
                {
                    b.Property<string>("FilterGroupName")
                        .HasColumnType("text")
                        .HasColumnName("filter_groupname");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("FilterGroupName");

                    b.ToTable("SearchFilters");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.TermsEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("TypeAccepted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_accepted");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VersionAccepted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_accepted");

                    b.HasKey("ResToken");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderLineEntity", b =>
                {
                    b.Property<Guid>("UpsellOrderLineGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("upsell_order_line_guid");

                    b.Property<string>("BitrixLineId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bitrix_line_id");

                    b.Property<int?>("BitrixProductId")
                        .HasColumnType("integer")
                        .HasColumnName("bitrix_product_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<bool>("IsFreeUnlimitedUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free_unlimited_uses");

                    b.Property<string>("LineStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("line_status");

                    b.Property<decimal>("LineTotalGross")
                        .HasColumnType("numeric")
                        .HasColumnName("line_total_gross");

                    b.Property<int>("Nights")
                        .HasColumnType("integer")
                        .HasColumnName("nights");

                    b.Property<int>("PartnerServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_service_id");

                    b.Property<int>("PricingModel")
                        .HasColumnType("integer")
                        .HasColumnName("pricing_model");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title_snapshot");

                    b.Property<int>("TotalGuests")
                        .HasColumnType("integer")
                        .HasColumnName("total_guests");

                    b.Property<decimal>("UnitPriceGross")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price_gross");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<PartnerServiceSnapshot>("UpsellDefinitionSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("partner_service_definition_snapshot");

                    b.Property<Guid>("UpsellOrderGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("upsell_order_guid");

                    b.HasKey("UpsellOrderLineGuid");

                    b.HasIndex("UpsellOrderGuid");

                    b.ToTable("upsell_order_lines");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderRecordEntity", b =>
                {
                    b.Property<Guid>("UpsellOrderGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("upsell_order_guid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<Guid?>("PaymentSessionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_session_guid");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_transaction_id");

                    b.Property<Guid?>("ReservationGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_guid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpsellOrderJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("upsell_order_json");

                    b.HasKey("UpsellOrderGuid");

                    b.HasIndex("ReservationGuid");

                    b.ToTable("upsell_order_records");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellVoucherEntity", b =>
                {
                    b.Property<Guid>("UpsellVoucherGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("upsell_voucher_guid");

                    b.Property<string>("CodeShort")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("code_short");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("qr_token");

                    b.Property<Guid>("ReservationGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_guid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UpsellOrderLineGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("upsell_order_line_guid");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("UpsellVoucherGuid");

                    b.HasIndex("CodeShort")
                        .IsUnique();

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("ReservationGuid")
                        .HasDatabaseName("idx_upsell_vouchers_reservation_guid");

                    b.HasIndex("UpsellOrderLineGuid")
                        .IsUnique();

                    b.HasIndex("Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("idx_upsell_vouchers_status_validity");

                    b.ToTable("upsell_vouchers");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerAgreedTerms", b =>
                {
                    b.HasOne("RentoomBooking.SharedClasses.Models.CustomerTermsAndConditionsSource", "TermsSource")
                        .WithMany()
                        .HasForeignKey("TermsSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermsSource");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderLineEntity", b =>
                {
                    b.HasOne("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderRecordEntity", "UpsellOrderRecord")
                        .WithMany("UpsellOrderLineEntities")
                        .HasForeignKey("UpsellOrderGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpsellOrderRecord");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderRecordEntity", b =>
                {
                    b.HasOne("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationRecordEntity", "ReservationRecord")
                        .WithMany("UpsellOrderRecords")
                        .HasForeignKey("ReservationGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReservationRecord");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellVoucherEntity", b =>
                {
                    b.HasOne("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderLineEntity", "UpsellOrderLine")
                        .WithOne("UpsellVoucher")
                        .HasForeignKey("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellVoucherEntity", "UpsellOrderLineGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpsellOrderLine");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationRecordEntity", b =>
                {
                    b.Navigation("UpsellOrderRecords");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderLineEntity", b =>
                {
                    b.Navigation("UpsellVoucher")
                        .IsRequired();
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.UpsellOrderRecordEntity", b =>
                {
                    b.Navigation("UpsellOrderLineEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
