// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentoomBooking.SharedClasses.Database;

#nullable disable

namespace RentoomBooking.SharedClasses.Migrations
{
    [DbContext(typeof(PostgresBookingDbContext))]
    [Migration("20260204090000_AddReservationTemplates")]
    partial class AddReservationTemplates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerAgreedTerms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgreedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClientBitrixId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReservationGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("TermsSourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TermsSourceId");

                    b.ToTable("customer_agreed_terms");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerTermsAndConditionsSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("customer_terms_sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zgoda na przetwarzanie danych osobowych przez serwis Rentoom (Administratora danych) w celu realizacji usług",
                            IsRequired = true,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Regulamin główny serwisu i akceptacja IdoBooking",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zgoda na komunikację i przesyłanie ofert przez WhatsApp",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zgoda na przetwarzanie danych w systemie CRM Bitrix24",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zgoda marketingowa na przesyłanie ofert handlowych",
                            IsRequired = false,
                            Link = "",
                            ValidFrom = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentAmenityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentAmenities");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentHashEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentHashes");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ApartmentInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("ApartmentInfos");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.DefinedAddonEntity", b =>
                {
                    b.Property<int>("IdoBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idobooking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdoBookingId"));

                    b.Property<string>("AddonDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("addon_definition");

                    b.Property<string>("AddonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addon_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<decimal>("PriceGross")
                        .HasColumnType("numeric")
                        .HasColumnName("price_gross");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric")
                        .HasColumnName("vat");

                    b.HasKey("IdoBookingId");

                    b.ToTable("defined_addons");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.RegistrationCardEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_mail");

                    b.Property<string>("GuestsData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("guests_data");

                    b.HasKey("ResToken");

                    b.ToTable("RegistrationCard");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.HasKey("ResToken");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationTemplateEntity", b =>
                {
                    b.Property<string>("TemplateKey")
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TemplateKey");

                    b.ToTable("reservation_templates");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.ReservationRecordEntity", b =>
                {
                    b.Property<Guid>("ReservationGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_guid");

                    b.Property<int?>("ClientBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("client_bitrix_id");

                    b.Property<string>("ConfirmationEmailBitrixId")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_email_bitrix_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DealBitrixId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_bitrix_id");

                    b.Property<int?>("IdoReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("ido_reservation_id");

                    b.Property<string>("IdoStatus")
                        .HasColumnType("text")
                        .HasColumnName("ido_status");

                    b.Property<Guid?>("PaymentSessionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_session_guid");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("ReservationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reservation_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ReservationGuid");

                    b.ToTable("reservation_records");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.SearchFiltersEntity", b =>
                {
                    b.Property<string>("FilterGroupName")
                        .HasColumnType("text")
                        .HasColumnName("filter_groupname");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("FilterGroupName");

                    b.ToTable("SearchFilters");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.Database.EFEntitites.TermsEntity", b =>
                {
                    b.Property<string>("ResToken")
                        .HasColumnType("text")
                        .HasColumnName("res_token");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("TypeAccepted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_accepted");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VersionAccepted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_accepted");

                    b.HasKey("ResToken");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("RentoomBooking.SharedClasses.Models.CustomerAgreedTerms", b =>
                {
                    b.HasOne("RentoomBooking.SharedClasses.Models.CustomerTermsAndConditionsSource", "TermsSource")
                        .WithMany()
                        .HasForeignKey("TermsSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermsSource");
                });
#pragma warning restore 612, 618
        }
    }
}
