name: PROD - Booking Website - app-prod-rentoombooking

on:
  push:
    branches:
      - main
    paths:
      - 'RentoomBookingWeb/**'
      - 'SharedClasses/**'
      - 'SharedFrontend/**'
      - '.github/workflows/main_app-prod-rentoombooking.yml'
  workflow_dispatch:

concurrency:
  group: app-prod-rentoombooking-main
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: app-prod-rentoombooking
  PROJECT_PATH: RentoomBookingWeb/RentoomBookingWeb.csproj
  PUBLISH_PATH: published-webapp
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore web app project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build web app project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish web app project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PUBLISH_PATH }}

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package-prod
          path: ${{ env.PUBLISH_PATH }}
          include-hidden-files: true

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package-prod
          path: ${{ env.PUBLISH_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID_APP_PROD_RENTOOMBOOKING }}
          tenant-id: ${{ vars.AZURE_TENANT_ID_PROD }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID_PROD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_PATH }}
          
